sudo: required

services:
  - docker

before_install:
- docker pull tianon/latex

script:
- mkdir _build
- pdflatex -output-directory _build "IRCI1/Algèbre Linéaire/Algèbre Linéaire - Nicolas Englebert.tex"
