language: r
pandoc: false
cache: packages
warnings_are_errors: false


before_install:
  - tlmgr install babel-french cancel pgfplots circuitikz titlepic fourier


install: echo 1

script:
- cd "IRCI4-PHYS/Mécanique quantique II/"
- mkdir _build
- pdflatex -interaction=nonstopmode -output-directory _build "Mécanique quantique II - Nicolas Englebert.tex"
