#!/bin/bash

set -ev
git diff --diff-filter=rd --name-only HEAD^^ | sed 's/\([^\/]*\/[^\/]*\/[^\/]*\/\).*/\1/g' | while read p; do dirname "$p"; done | awk '!a[$0]++' | while read p
do
if $(echo "$p" | grep -q "Builder"); then
continue
elif [ "$p" == "." ]; then
continue
else
(cd "$p"/ && mkdir -p build && exec find *.tex | while read p; do pdflatex -interaction=nonstopmode -halt-on-error -output-directory build "$p"; done)
fi
done
git add -A
echo $(git status)